name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=512m" -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Create Android project folder
        run: |
          cd Mobile
          flutter create --org com.nexcall --platforms=android .

      - name: Force Android Compile SDK to 36
        run: |
          cat << 'EOF' >> Mobile/android/build.gradle
          subprojects {
              afterEvaluate { project ->
                  if (project.hasProperty("android")) {
                      project.android {
                          compileSdk 36
                          compileSdkVersion 36
                      }
                  }
              }
          }
          EOF

      - name: Get Flutter packages
        run: |
          cd Mobile
          flutter pub get

      - name: Build release APK
        run: |
          cd Mobile
          flutter build apk --release --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexcall-release-apk
          path: Mobile/build/app/outputs/flutter-apk/app-release.apk
