name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=512m" -Dorg.gradle.daemon=false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Recreate Android project folder
        run: |
          cd Mobile
          flutter create --org com.nexcall --platforms=android .

      - name: Force Android SDK compileSdkVersion and minSdkVersion
        run: |
          cat << 'EOF' >> Mobile/android/build.gradle
          subprojects {
              afterEvaluate { project ->
                  if (project.hasProperty("android")) {
                      project.android {
                          compileSdk 34
                          compileSdkVersion 34
                          defaultConfig {
                              minSdk 24
                              minSdkVersion 24
                          }
                      }
                  }
              }
          }
          EOF

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Get packages
        run: |
          cd Mobile
          flutter pub get

      - name: Build Release APK
        run: |
          cd Mobile
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nexcall-app-release
          path: Mobile/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
